# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98d519200a51beabddfab768e7a51bf3b52300062c80887c6846d76c9d797a80400ff010c7cc1244ff18fa06df6fd9869bcb6242bb96f4103aabdaa1b5a59a5b

test:
  secret_key_base: 8458834f15366663b94e9bf88b091b51e668903fdd4849230b1831b2a38bbded38526092a19622b947be56f0815e9c2f88d244fdf86ae9580839ac41bfd5b377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
